### ISSUE TITLE
mesa is broken in sumo

### ISSUE THREAD

**Issue by fmhess** [Angstrom-distribution/meta-angstrom#22]
when building an image with sumo, during 

meta-angstrom/recipes-tweaks/mesa/mesa_18.1.3.bb:do_compile

I get:

make[4]: *** No rule to make target '/usr/share/wayland-protocols/unstable/linux-dmabuf/linux-dmabuf-unstable-v1.xml', needed by 'drivers/dri2/linux-dmabuf-unstable-v1-client-protocol.h'.  Stop.

any suggestions on how to work around?

**Comment by koenkooi** [comment]
Do you have those files installed on your host? It could be that mesa is getting confused and picking the wrong headers.
It shouldn't do that, but would narrow down the problem.

**Comment by fmhess** [comment]
I believe the problem was fixed in openembedded-core by this patch (which kraj signed off on)

https://github.com/openembedded/openembedded-core/blob/master/meta/recipes-graphics/mesa/files/0006-use-PKG_CHECK_VAR-for-defining-WAYLAND_PROTOCOLS_DAT.patch

So maybe the fix just needs to be added to the sumo branch of meta-angstrom/recipes-tweaks/mesa/

**Comment by fmhess** [comment]
For the record, adding the 0006-use-PKG_CHECK_VAR-for-defining-WAYLAND_PROTOCOLS_DAT.patch worked, although you also need to add the following to the bb file:

EXTRA_OEMAKE += "WAYLAND_PROTOCOLS_DATADIR=${STAGING_DATADIR}/wayland-protocols"

Utimately I wound up disabling wayland entirely from the distro features, since the build of qtwayland is also broken.
