### ISSUE TITLE
libdrm patch fails

### ISSUE THREAD

**Issue by fmhess** [Angstrom-distribution/meta-angstrom#23]
Sometime in the past few days, libdrm has starting failing to patch (I'm using the sumo branch):

ERROR: libdrm-2.4.96-r0 do_patch: Command Error: 'quilt --quiltrc /home/fmhess/git/fluke-cda-setup/angstrom-v2018.06-sumo-fluke-cda-manifest/build/tmp-angstrom-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/libdrm/2.4.96-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch installtests.patch
patching file tests/Makefile.am
Hunk #1 FAILED at 45.
1 out of 1 hunk FAILED -- rejects in file tests/Makefile.am
Patch installtests.patch does not apply (enforce with -f)
ERROR: libdrm-2.4.96-r0 do_patch: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /home/fmhess/git/fluke-cda-setup/angstrom-v2018.06-sumo-fluke-cda-manifest/build/tmp-angstrom-glibc/work/armv7at2hf-neon-angstrom-linux-gnueabi/libdrm/2.4.96-r0/temp/log.do_patch.9857
ERROR: Task (/home/fmhess/git/fluke-cda-setup/angstrom-v2018.06-sumo-fluke-cda-manifest/layers/meta-angstrom/recipes-tweaks/drm/libdrm_2.4.96.bb:do_patch) failed with exit code '1'

**Comment by koenkooi** [comment]
I think I know what's happening here, I have ```PATCHTOOL = "git"``` in local.conf, which has no problem with that patch. The default quilt tool however does have problems with it, even after regenerating the patch against the 'libdrm-2.4.96' upstream tag.
I should have a fix ready later today.
