### ISSUE TITLE
Updating old Angstrom Kernel

### ISSUE THREAD

**Issue by wkrd** [Angstrom-distribution/meta-angstrom#24]
Hello, I have some old Beaglebone Blacks with an old Angstrom distribution (Angstrom v2012.12 Kernel 3.8.13).   Although is still the most recent Angstrom image that Beaglebone Black provides on their website.

We are having issues where I2C bus is getting hung, and I have read that there is a recovery mechanism built into Kernels v 3.10+ ), so I am trying to upgrade to a later kernel.  If I upgrade to V 3.X, should I be able to drop a replacement into the /boot/ folder?  If so, I would want to just upgrade to 3.10+

I've been able to compile a the latest kernel using the yocto-docker docker image, but it is 4.X kernel but I'm assuming I need a 3.X kernel to avoid rebuilding everything else on the system.
I got some strange errors trying to build  the 'angstrom-v2013.12-yocto1.5' branch, but mabey that has the 3.X kernel I want.

Any general ideas on the best way to proceed?

**Comment by koenkooi** [comment]
If you copy over the new kernel and devicetree, it should "Just Work". With Angstrom v2018.06 I use kernel 4.19.7 on BBW and BBB without any issues, but DT overlays won't work.
