### ISSUE TITLE
do_rootfs: No manifest generated from: angstrom-libc-fixup-hack

### ISSUE THREAD

**Issue by feddischson** [Angstrom-distribution/meta-angstrom#36]
Hi,

I am trying to upgrade a layer to support angstrom warrior, but getting the following error:
```
do_rootfs: No manifest generated from: angstrom-libc-fixup-hack in ....../conf/../layers/meta-angstrom/recipes-angstrom/angstrom/angstrom-libc-fixup-hack.bb
```
Is there something which needs to be considered regarding this angstrom-libc-fixup-hack?

I am on the `github/angstrom-v2019.06-warrior` branch for meta-angstrom.

**Comment by koenkooi** [comment]
I don't see that particular error, but the fixup shouldn't be needed anymore, so I've removed it in 68644217c63fb961cc539ce64d11c13cfe741107

**Comment by feddischson** [comment]
Thanks, that worked in my case.
