### ISSUE TITLE
Yocto dunfell

### ISSUE THREAD

**Issue by marioecht** [Angstrom-distribution/meta-angstrom#46]
Can Yocto dunfell branch be prepared?

**Comment by koenkooi** [comment]
A meta-angstrom branch can be prepared soon-ish, a proper angstrom-manifest will take longer.

**Comment by marioecht** [comment]
The prepared branch would be enough. I can test then.

**Comment by koenkooi** [comment]
Thanks! I just pushed the angstrom-v2020.06-dunfell branch, which is the same as angstrom-v2019.12-zeus.
