### ISSUE TITLE
Yocto gatesgarth

### ISSUE THREAD

**Issue by marioecht** [Angstrom-distribution/meta-angstrom#50]
I have created an angstrom-v2020.12-gatesgarth branch with the appropriate modifications.
https://github.com/marioecht/meta-angstrom/tree/angstrom-v2020.12-gatesgarth

Can you create an angstrom-v2020.12-gatesgarth branch based on the angstrom-v2020.06-dunfell branch?

**Comment by koenkooi** [comment]
Done! Thanks for your work!
